-- Table Country, represents Country objects and is accessed via CountryDao
CREATE TABLE Country (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code CHAR(2) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

-- Table City, represents City objects and is accessed via CityDao
CREATE TABLE City (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (country_id) REFERENCES Country(id) ON DELETE CASCADE
);

-- Table Measurement, represents Measurement objects and is accessed via MeasurementDao
CREATE TABLE Measurement (
    city_id INTEGER NOT NULL,
    datetime TIMESTAMP NOT NULL,
    temp FLOAT,
    temp_feels_like FLOAT,
    temp_min FLOAT,
    temp_max FLOAT,
    pressure INTEGER,
    humidity INTEGER,
    wind_speed FLOAT,
    wind_direction INTEGER,
    wind_gust FLOAT,
    clouds INTEGER,
    condition_id INTEGER,
    PRIMARY KEY (city_id, datetime),
    FOREIGN KEY (city_id) REFERENCES City(id) ON DELETE CASCADE
);
